### ISSUE TITLE
index.html not loading in popup window

### ISSUE THREAD

**Issue by kedarkhetia** [dkbhadeshiya/Autor#1]
Hi,
The menubar is not loading the index.html provided in the constructor of mb (file: index.js).
index.html is provided using 
var mb = menubar({index: "./index.html"});

**Comment by dkbhadeshiya** [comment]
Actually menubar loads the index.html by default why do you have to provide it as option?
Anyways try :
`var pathString = path.join('file:" + __dirname + '/index.html'); 
var mb = menubar({index : pathString });` 
This will work it out...
Here the 'file:/' is important as we are loading page from fs instead of http req. 
And in future avoid using relative paths, instead use absolute paths.

**Comment by kedarkhetia** [comment]
Firstly there are two things which you might have missed in your project
1. menubar is not loading your index.html
2. your solution didn't worked.

I think the issue is in menubar module itself, as in their example when we try to pass any other html file that would work as index file it is not working, for example

```
var mb = menubar({index: "main.html"});
```

will not load anything on the popup screen.

**Comment by kedarkhetia** [comment]
Also, it doesn't make much difference here about using the absolute or relative path. Try not to close the issue until it is not resolved.
